[tool.black]
line-length = 79
target-version = ["py39"]
skip-string-normalization = true

[tool.flake8]
max-line-length = 79
ignore = ["E203", "W503"]

[tool.isort]
profile = "black"
line_length = 79
