# Generated by Django 5.2.1 on 2025-06-04 11:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('drf_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.DecimalField(
                decimal_places=2, default=True, max_digits=10
            ),
            preserve_default=False,
        ),
    ]
