# Generated by Django 5.2.1 on 2025-06-04 12:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('drf_api', '0002_item_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=10
            ),
        ),
    ]
